title = "Prey Predator Example"

[author]
name = "Emanuel Lima"
email = "emanuel@block.science"
version = 0.1

[simulations]
[simulations.alpha]
aggregation = ""
sweep = ""
enabled = true
initial_conditions = "initial_conditions_alpha"
params = "parameters_alpha"
n_runs = 1
timesteps = 5
pipeline = [
    [
        [
            "prey_policy",
            "predator_policy",
        ],
        [
            "state_prey_update",
            "state_predator_update",
        ],
    ],
]

[simulations.beta]
aggregation = ""
enabled = false
sweep = ""
initial_conditions = "initial_conditions_beta"
params = "parameters_beta"
n_runs = 5
timesteps = 200
pipeline = [
    [
        [
            "prey_policy",
            "predator_policy",
        ],
        [
            "state_prey_update",
            "state_predator_update",
        ],
    ],
]
# Invariant: All policies come in the same list before the SUFs
# Default aggregation is concatenation
