name = "cadCAD"

[install]
completion = false
quiet = false
optimize = 2

[application]
incremental = true
filter_stdlibs = false

[application.precompile]
execution_file = ["deps/precompile.jl"]

[download]
host = "github.com"
user = "cadCAD-org"
repo = "cadCAD.jl"
