# My simulation's TOML

title = "Prey Predator Example"

[author]
name = "Emanuel Lima"
email = "emanuel@block.science"
version = 0.1

[state]
prey_population = "Float64"
predator_population = "Float64"

[simulations]
[simulations.alpha]
enabled = false
literal_init = true
initial_conditions = { prey_population = 79.5, predator_population = 72.0 }
params = { prey_birth_rate = 1.0, predator_birth_rate = 0.01, predator_death_const = 1.0, prey_death_const = 0.03, dt = 0.1 }
n_runs = 5
timesteps = 200
pipeline = [
    { predator_births = "p_predator_births", prey_births = "p_prey_births", predator_deaths = "p_predator_deaths", prey_deaths = "p_prey_deaths" },
    { prey_population = "s_prey_population", predator_population = "s_predator_population" },
]

[simulations.beta]
enabled = true
literal_init = true
initial_conditions = { prey_population = 97.2, predator_population = 17.6 }
params = { prey_birth_rate = 0.9, predator_birth_rate = 0.05, predator_death_const = 1.1, prey_death_const = 0.07, dt = 0.2 }
n_runs = 5
timesteps = 200
pipeline = [
    { predator_births = "p_predator_births", prey_births = "p_prey_births", predator_deaths = "p_predator_deaths", prey_deaths = "p_prey_deaths" },
    { prey_population = "s_prey_population", predator_population = "s_predator_population" },
]
