title = "Prey Predator Example"

[author]
name = "Emanuel Lima"
email = "emanuel@block.science"
version = 0.1

[simulations]
[simulations.alpha]
enabled = true
initial_conditions = "initial_conditions_alpha"
params = "parameters_alpha"
n_runs = 5
timesteps = 200
pipeline = [
    ["policy_prey_update", "policy_predator_update"],
    ["state_prey_update", "state_predator_update"],
]

[simulations.beta]
enabled = false
initial_conditions = "initial_conditions_beta"
params = "parameters_beta"
n_runs = 5
timesteps = 200
pipeline = [
    ["policy_prey_update", "policy_predator_update"],
    ["state_prey_update", "state_predator_update"],
]
